spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.104:3306/sell?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  freemarker:
    request-context-attribute: request
server:
  context-path: /sell
wechat:
  mpAppId: wxb17d3813443e8403 #微信公众平台AppID
  mpAppSecret: ff34e395904861c746b23a9a54eefd22 #微信公众平台秘钥


